sudo: required
services:
  - docker

before_install:
  - docker build -t zhdanovskiy/docker-react -f Dockerfile.dev .

script:
  - docker run zhdanovskiy/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  backet_name: "elasticbeanstalk-us-east-1-114096054274"
  backet_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
